import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import { Layout } from '@/components/craft';

const font = Manrope({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return <Layout className={font.className}>{children}</Layout>;
}
